[program:multibuilder]
command=/home/nimrod_rotem/web-projects/Nimo/multiagent/deploy/run-production.sh
directory=/home/nimrod_rotem/web-projects/Nimo/multiagent
user=nimrod_rotem
umask=0077
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopsignal=TERM
stopwaitsecs=25
stopasgroup=true
killasgroup=true
redirect_stderr=true
stdout_logfile=/var/log/multibuilder.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=3
environment=PYTHONUNBUFFERED="1"
priority=250
