"""Alembic environment for the dashboard's PostgreSQL state.

The URL comes from TMUX_DASH_DB_URL, the same variable the app reads, so
migrations can never target a different database than the running dashboard.
It is deliberately NOT written into alembic.ini, which is committed and would
otherwise carry the password.

There are no ORM models here: the app talks to psycopg directly, so
`target_metadata` stays None and revisions are written by hand rather than
autogenerated.
"""

from __future__ import annotations

import os
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = None


def _database_url() -> str:
    url = os.environ.get("TMUX_DASH_DB_URL", "").strip()
    if not url:
        raise RuntimeError(
            "TMUX_DASH_DB_URL is not set; load the app's .env before running alembic"
        )
    # psycopg 3 is what the app uses; SQLAlchemy needs the driver named
    # explicitly or it reaches for psycopg2, which is not installed.
    if url.startswith("postgresql://"):
        url = url.replace("postgresql://", "postgresql+psycopg://", 1)
    return url


def run_migrations_offline() -> None:
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    section["sqlalchemy.url"] = _database_url()
    connectable = engine_from_config(
        section, prefix="sqlalchemy.", poolclass=pool.NullPool
    )
    with connectable.connect() as connection:
        context.configure(connection=connection, target_metadata=target_metadata)
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
